<a href="https://colab.research.google.com/github/Aysha2004/INTERNSHIP_2025/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDEXING

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.3,2.0,3.1],[2.3,3.4,5.0]])
print(b)

[[1.3 2.  3.1]
 [2.3 3.4 5. ]]


In [ ]:
#Get dimension
a.ndim

1

In [ ]:
#Get shape
b.shape

(2, 3)

In [ ]:
#Get Type
a.dtype

dtype('int16')

In [ ]:
#Get size in bytes
a.itemsize

2

In [ ]:
#Get total size
#a.size * a.itemsize or
a.nbytes

6

In [ ]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element
c[1,4]

np.int64(12)

In [ ]:
#Get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#Get a specific column
c[:, 1]

array([2, 9])

In [ ]:
#Getting a little more fancy ,to get continuous elements but from random places[row number, startindex:endindex:stepsize]
c[1, 1:7:2]


array([ 9, 11,  4])

In [ ]:
c[1,5] = 4
print(c)

c[:, 5] = [5,0]
print(c)

[[ 4  4  4  4  4  4  4]
 [ 4  9 10 11 12  4 14]]
[[ 4  4  4  4  4  5  4]
 [ 4  9 10 11 12  0 14]]


In [ ]:
#3d example
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific elements
d[1, 0, 1]

np.int64(6)

In [ ]:
d[:,0,:]

array([[1, 2],
       [5, 6]])

In [ ]:
#replace
d[1,:,:] = [[8,9],[9,0]]
print(d)

[[[1 2]
  [8 9]]

 [[8 9]
  [9 0]]]


INITIALIZING DIFFERENT TYPES OF ARRAYS

In [ ]:
#All 0s matrix
np.zeros((2,3), dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
#All 1s matrix
np.ones((2,3,4), dtype = 'int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
#Any other number
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [ ]:
#Any other number (full_like)
np.full_like(a, 7)

array([7, 7, 7], dtype=int16)

In [ ]:
#Random decimal numbers
np.random.rand(2,3)

array([[0.52039831, 0.36194455, 0.09957779],
       [0.16528447, 0.42176092, 0.99118455]])

In [ ]:
#Random integer values
np.random.randint(-3,8, size =  (3,4))

array([[ 1,  4, -3,  3],
       [-3, -2,  0,  4],
       [-3,  6, -2,  3]])