<a href="https://colab.research.google.com/github/Aysha2004/INTERNSHIP_2025/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x_zeroes = np.zeros(10)
print(x_zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
sequence = np.arange(10,51)
print(sequence)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
reshaped_arr = np.reshape(arr, (3,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
rev_arr = np.flip(arr)
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [ ]:
replace_arr = np.where(arr % 2 != 0, -1, arr)
print(replace_arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

print("Shape: ", b.shape)
print("Size: ",b.size)

[[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Size:  6


In [ ]:
c = np.identity(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
c = np.eye(4) #can use ".eye" for identity matrix
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
d = np.array([1,2,3,4,5])
print("Mean: ", np.mean(d))
print("Median: ", np.median(d))
print("Standard Deviation: ", np.std(d))

Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951


In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print("Horizontal: ", np.hstack((x,y)))
print("Vertical: ")
print( np.vstack((x,y)))

Horizontal:  [1 2 3 4 5 6]
Vertical: 
[[1 2 3]
 [4 5 6]]


In [ ]:
even_num = arr[arr.reshape(-1) % 2 == 0]  #reshape(-1) is to flatten the array
print(even_num)

[2 4 6 8]
